/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkloadRouteImport } from './routes/workload'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SkillPacksRouteImport } from './routes/skill-packs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GatewayRouteImport } from './routes/gateway'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as CustomFieldsRouteImport } from './routes/custom-fields'
import { Route as CronRouteImport } from './routes/cron'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as BoardGroupsRouteImport } from './routes/board-groups'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as BoardsIndexRouteImport } from './routes/boards.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as BoardsBoardIdIndexRouteImport } from './routes/boards.$boardId.index'
import { Route as BoardsBoardIdMemoryRouteImport } from './routes/boards.$boardId.memory'

const WorkloadRoute = WorkloadRouteImport.update({
  id: '/workload',
  path: '/workload',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillPacksRoute = SkillPacksRouteImport.update({
  id: '/skill-packs',
  path: '/skill-packs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayRoute = GatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomFieldsRoute = CustomFieldsRouteImport.update({
  id: '/custom-fields',
  path: '/custom-fields',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardGroupsRoute = BoardGroupsRouteImport.update({
  id: '/board-groups',
  path: '/board-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleRoute,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => PeopleRoute,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => BoardsRoute,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)
const BoardsBoardIdIndexRoute = BoardsBoardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const BoardsBoardIdMemoryRoute = BoardsBoardIdMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/board-groups': typeof BoardGroupsRoute
  '/boards': typeof BoardsRouteWithChildren
  '/cron': typeof CronRoute
  '/custom-fields': typeof CustomFieldsRoute
  '/flow': typeof FlowRoute
  '/gateway': typeof GatewayRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skill-packs': typeof SkillPacksRoute
  '/skills': typeof SkillsRoute
  '/tags': typeof TagsRoute
  '/workload': typeof WorkloadRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/people/$personId': typeof PeoplePersonIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/boards/': typeof BoardsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/boards/$boardId/memory': typeof BoardsBoardIdMemoryRoute
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/board-groups': typeof BoardGroupsRoute
  '/cron': typeof CronRoute
  '/custom-fields': typeof CustomFieldsRoute
  '/flow': typeof FlowRoute
  '/gateway': typeof GatewayRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/skill-packs': typeof SkillPacksRoute
  '/skills': typeof SkillsRoute
  '/tags': typeof TagsRoute
  '/workload': typeof WorkloadRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/boards': typeof BoardsIndexRoute
  '/people': typeof PeopleIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/boards/$boardId/memory': typeof BoardsBoardIdMemoryRoute
  '/boards/$boardId': typeof BoardsBoardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/board-groups': typeof BoardGroupsRoute
  '/boards': typeof BoardsRouteWithChildren
  '/cron': typeof CronRoute
  '/custom-fields': typeof CustomFieldsRoute
  '/flow': typeof FlowRoute
  '/gateway': typeof GatewayRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skill-packs': typeof SkillPacksRoute
  '/skills': typeof SkillsRoute
  '/tags': typeof TagsRoute
  '/workload': typeof WorkloadRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/people/$personId': typeof PeoplePersonIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/boards/': typeof BoardsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/boards/$boardId/memory': typeof BoardsBoardIdMemoryRoute
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agents'
    | '/analytics'
    | '/approvals'
    | '/board-groups'
    | '/boards'
    | '/cron'
    | '/custom-fields'
    | '/flow'
    | '/gateway'
    | '/login'
    | '/people'
    | '/projects'
    | '/settings'
    | '/skill-packs'
    | '/skills'
    | '/tags'
    | '/workload'
    | '/agents/$agentId'
    | '/agents/new'
    | '/boards/$boardId'
    | '/people/$personId'
    | '/projects/$projectId'
    | '/boards/'
    | '/people/'
    | '/projects/'
    | '/boards/$boardId/memory'
    | '/boards/$boardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/agents'
    | '/analytics'
    | '/approvals'
    | '/board-groups'
    | '/cron'
    | '/custom-fields'
    | '/flow'
    | '/gateway'
    | '/login'
    | '/settings'
    | '/skill-packs'
    | '/skills'
    | '/tags'
    | '/workload'
    | '/agents/$agentId'
    | '/agents/new'
    | '/people/$personId'
    | '/projects/$projectId'
    | '/boards'
    | '/people'
    | '/projects'
    | '/boards/$boardId/memory'
    | '/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agents'
    | '/analytics'
    | '/approvals'
    | '/board-groups'
    | '/boards'
    | '/cron'
    | '/custom-fields'
    | '/flow'
    | '/gateway'
    | '/login'
    | '/people'
    | '/projects'
    | '/settings'
    | '/skill-packs'
    | '/skills'
    | '/tags'
    | '/workload'
    | '/agents/$agentId'
    | '/agents/new'
    | '/boards/$boardId'
    | '/people/$personId'
    | '/projects/$projectId'
    | '/boards/'
    | '/people/'
    | '/projects/'
    | '/boards/$boardId/memory'
    | '/boards/$boardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BoardGroupsRoute: typeof BoardGroupsRoute
  BoardsRoute: typeof BoardsRouteWithChildren
  CronRoute: typeof CronRoute
  CustomFieldsRoute: typeof CustomFieldsRoute
  FlowRoute: typeof FlowRoute
  GatewayRoute: typeof GatewayRoute
  LoginRoute: typeof LoginRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SkillPacksRoute: typeof SkillPacksRoute
  SkillsRoute: typeof SkillsRoute
  TagsRoute: typeof TagsRoute
  WorkloadRoute: typeof WorkloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workload': {
      id: '/workload'
      path: '/workload'
      fullPath: '/workload'
      preLoaderRoute: typeof WorkloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-packs': {
      id: '/skill-packs'
      path: '/skill-packs'
      fullPath: '/skill-packs'
      preLoaderRoute: typeof SkillPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway': {
      id: '/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof GatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-fields': {
      id: '/custom-fields'
      path: '/custom-fields'
      fullPath: '/custom-fields'
      preLoaderRoute: typeof CustomFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-groups': {
      id: '/board-groups'
      path: '/board-groups'
      fullPath: '/board-groups'
      preLoaderRoute: typeof BoardGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/people/': {
      id: '/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/boards/': {
      id: '/boards/'
      path: '/'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof BoardsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof BoardsRoute
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/boards/$boardId/': {
      id: '/boards/$boardId/'
      path: '/'
      fullPath: '/boards/$boardId/'
      preLoaderRoute: typeof BoardsBoardIdIndexRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/boards/$boardId/memory': {
      id: '/boards/$boardId/memory'
      path: '/memory'
      fullPath: '/boards/$boardId/memory'
      preLoaderRoute: typeof BoardsBoardIdMemoryRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsNewRoute: typeof AgentsNewRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsNewRoute: AgentsNewRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface BoardsBoardIdRouteChildren {
  BoardsBoardIdMemoryRoute: typeof BoardsBoardIdMemoryRoute
  BoardsBoardIdIndexRoute: typeof BoardsBoardIdIndexRoute
}

const BoardsBoardIdRouteChildren: BoardsBoardIdRouteChildren = {
  BoardsBoardIdMemoryRoute: BoardsBoardIdMemoryRoute,
  BoardsBoardIdIndexRoute: BoardsBoardIdIndexRoute,
}

const BoardsBoardIdRouteWithChildren = BoardsBoardIdRoute._addFileChildren(
  BoardsBoardIdRouteChildren,
)

interface BoardsRouteChildren {
  BoardsBoardIdRoute: typeof BoardsBoardIdRouteWithChildren
  BoardsIndexRoute: typeof BoardsIndexRoute
}

const BoardsRouteChildren: BoardsRouteChildren = {
  BoardsBoardIdRoute: BoardsBoardIdRouteWithChildren,
  BoardsIndexRoute: BoardsIndexRoute,
}

const BoardsRouteWithChildren =
  BoardsRoute._addFileChildren(BoardsRouteChildren)

interface PeopleRouteChildren {
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  BoardGroupsRoute: BoardGroupsRoute,
  BoardsRoute: BoardsRouteWithChildren,
  CronRoute: CronRoute,
  CustomFieldsRoute: CustomFieldsRoute,
  FlowRoute: FlowRoute,
  GatewayRoute: GatewayRoute,
  LoginRoute: LoginRoute,
  PeopleRoute: PeopleRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SkillPacksRoute: SkillPacksRoute,
  SkillsRoute: SkillsRoute,
  TagsRoute: TagsRoute,
  WorkloadRoute: WorkloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
